name: flutter_json_localization_generator
description: Generator for json localizations.
version: 0.0.1
author: James Peter Moore <jamesmoore255@gmail.com>
homepage:

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  http: ^0.12.0
#  meta: ^1.1.7
  csv: ^4.0.3
  recase: ^2.0.1
  code_builder: ^3.2.0
  dart_style: ^1.2.7
  source_gen: ^0.9.0
  build: ^1.2.0
  analyzer: ^0.38.4
  collection: ^1.14.11

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  pedantic: ^1.8.0
  build_test: ^0.10.3
  build_runner: ^1.0.0

